# Generated by Django 4.2.4 on 2023-08-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preco')),
                ('categoria', models.CharField(default='cat', max_length=20, verbose_name='Categoria')),
                ('ingredientes', models.TextField(max_length=300, verbose_name='Ingredientes')),
            ],
        ),
    ]
