# Generated by Django 4.2.4 on 2023-08-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='cat', max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(default='cat', max_length=11, verbose_name='cpf')),
                ('rg', models.CharField(default='cat', max_length=11, verbose_name='rg')),
                ('logradouro', models.CharField(default='cat', max_length=100, verbose_name='logradouro')),
                ('cidade', models.CharField(default='cat', max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(default='cat', max_length=2, verbose_name='uf')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='cat', max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, default='cat', max_digits=8, verbose_name='Preco')),
                ('categoria', models.CharField(default='cat', max_length=40, verbose_name='categoria')),
                ('sabor', models.CharField(default='cat', max_length=20, verbose_name='sabor')),
                ('ingredientes', models.TextField(default='cat', max_length=300, verbose_name='Ingredientes')),
            ],
        ),
    ]
